### PR TITLE
#163388130 create swagger API documentation

### PR DESCRIPTION
**Pull request by Arusey**
**What does this PR do?**
It creates documentation of the Author's Haven API using swagger which is an API documentation tool.

**Description of the tasks completed**
-creation a swagger.py file that implements the automated generation of the API during the -development of the endpoints
-created a route `api/v1/docs` for viewing the API documentation on the browser

**How can this be manually tested?**
After cloning the repo, cd into it and run the server, go to the `api/v1/docs` and view the browser documentation

**Any background context you want to provide?**
None

**What are the relevant pivotal tracker stories?**
#163388130

### CODE REVIEW

**Comment by dev-jey** [comment]
Hey Kevin, I have checked out the documentation and it looks fine. Nice work.
In the `relevant pt stories` part of the PR, change it to a clickable link.

**Comment by sirghiny** [comment]
Looks good. Just one thing, could you add links to the Heroku deployment and swagger docs to the README below the badges, it makes it easier for a new user to navigate to them.

**Comment by Arusey** [comment]
Makes sense...I will do them Asap

**Comment by Arusey** [comment]
done

**Pull request merged**
